name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload-release-zip:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip repository
        run: |
          zip -r Codec-Graph-Release.zip .
      - name: Upload Release zip to Release
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: Codec-Graph-Release.zip
          tag: ${{ github.ref }}
          file_glob: true

  windows-build:
    name: Build app for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install pyinstaller
        run: pip3 install pyinstaller
      - name: Build
        run: pyinstaller --onefile --windowed --icon=./Resources/Icon.ico --add-data "./Resources/Icon.ico;." Codec-Graph.py
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Codec-Graph Windows
          path: dist/Codec-Graph.exe
      - name: Upload Windows exe to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: dist/Codec-Graph.exe
          tag: ${{ github.ref }}
          file_glob: true
