name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  macos-build:
    name: Build app for macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: python3 macOS-build/setup.py py2app
      - name: Create zip
        run: cd dist; zip -r ../Codec-Graph.zip Codec-Graph.app
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Codec-Graph macOS
          path: Codec-Graph.zip
      # - name: Upload to Release
      #   if: github.event_name == 'release'
      #   uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
      #   with:
      #     repo_token: ${{ secrets.TOKEN }}
      #     file: FindOCVersion.app.zip
      #     tag: ${{ github.ref }}
      #     file_glob: true
  windows-build:
    name: Build app for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install pyinstaller
        run: pip3 install pyinstaller
      - name: Build
        run: pyinstaller --onefile --windowed --icon=./Resources/Icon.ico --add-data "./Resources/Icon.ico;." Codec-Graph.py
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Codec-Graph Windows
          path: dist/Codec-Graph.exe
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: dist/Codec-Graph.exe
          tag: ${{ github.ref }}
          file_glob: true
